import React, { useEffect, useState } from 'react';
import axios from 'axios';
import Intake from './Intake';

const Dashboard = ({ user, onLogout }) => {
  const [evidence, setEvidence] = useState([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState({});
  const [selectedEvidence, setSelectedEvidence] = useState(null);
  const [showDetails, setShowDetails] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  const fetchEvidence = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get('http://127.0.0.1:8000/api/evidence', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setEvidence(response.data);
    } catch (err) {
      if (err.response?.status === 401) onLogout();
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEvidence();
  }, []);

  const updateStatus = async (id, newStatus) => {
    const technician = user.username;
    try {
      const token = localStorage.getItem('token');
      await axios.patch(`http://127.0.0.1:8000/api/evidence/${id}/status`, null, {
        params: { new_status: newStatus, technician },
        headers: { Authorization: `Bearer ${token}` }
      });
      fetchEvidence();
      alert(`Status updated to ${newStatus}`);
    } catch (err) {
      alert('Update failed: ' + (err.response?.data?.detail || err.message));
    }
  };

  const uploadFile = async (id, file) => {
    if (!file) return;
    const formData = new FormData();
    formData.append('file', file);
    
    setUploading(prev => ({ ...prev, [id]: true }));
    try {
      const token = localStorage.getItem('token');
      const response = await axios.post(`http://127.0.0.1:8000/api/evidence/${id}/upload`, formData, {
        headers: { Authorization: `Bearer ${token}` }
      });
      alert(`File uploaded successfully!\nHash: ${response.data.hash.substring(0, 32)}...`);
      fetchEvidence();
    } catch (err) {
      alert('Upload failed: ' + (err.response?.data?.detail || err.message));
    } finally {
      setUploading(prev => ({ ...prev, [id]: false }));
    }
  };

  const deleteEvidence = async (id, caseNumber) => {
    if (window.confirm(`Are you sure you want to delete evidence "${caseNumber}"? This action cannot be undone.`)) {
      try {
        const token = localStorage.getItem('token');
        await axios.delete(`http://127.0.0.1:8000/api/evidence/${id}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        alert('Evidence deleted successfully');
        fetchEvidence();
      } catch (err) {
        alert('Delete failed: ' + (err.response?.data?.detail || err.message));
      }
    }
  };

  const downloadReport = async (item) => {
    try {
      // Create a simple text report
      const report = `
TRACELOCK FORENSIC REPORT
=========================
Generated: ${new Date().toLocaleString()}
Generated by: ${user.username} (${user.role})

EVIDENCE DETAILS
---------------
Case Number: ${item.case_number}
Description: ${item.description}
Category: ${item.category}
Status: ${item.status}
Created: ${new Date(item.created_at).toLocaleString()}

FORENSIC INTEGRITY
------------------
SHA-256 Hash: ${item.hash_value || 'Not calculated'}
File Attached: ${item.file_name || 'No file attached'}
File Size: ${item.file_size ? (item.file_size / 1024).toFixed(2) + ' KB' : 'N/A'}

This report is digitally signed by TraceLock Forensic System
      `;
      
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${item.case_number}_Forensic_Report.txt`;
      a.click();
      URL.revokeObjectURL(url);
      alert('Report downloaded successfully');
    } catch (err) {
      alert('Report generation failed');
    }
  };

  const viewDetails = async (id) => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`http://127.0.0.1:8000/api/evidence/${id}/details`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setSelectedEvidence(response.data);
      setShowDetails(true);
    } catch (err) {
      alert('Failed to load details');
    }
  };

  const getStatusColor = (status) => {
    const colors = { 
      'Intake': '#f59e0b', 
      'Scanning': '#3b82f6', 
      'Analyzing': '#8b5cf6', 
      'Completed': '#10b981', 
      'Archived': '#64748b' 
    };
    return colors[status] || '#6b7280';
  };

  const getStatusOptions = () => {
    if (user.role === 'viewer') return [];
    return ['Intake', 'Scanning', 'Analyzing', 'Completed', 'Archived'];
  };

  const filteredEvidence = evidence.filter(item =>
    item.case_number?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.description?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) return <div style={styles.loading}>Loading Dashboard...</div>;

  return (
    <div style={styles.container}>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <h1 style={styles.title}>🔒 TraceLock Forensic Suite</h1>
          <p style={styles.subtitle}>Secure Evidence Management System</p>
        </div>
        <div style={styles.userInfo}>
          <div style={styles.userDetails}>
            <span style={styles.userRole}>{user.role.toUpperCase()}</span>
            <span style={styles.userName}>{user.username}</span>
          </div>
          <button onClick={onLogout} style={styles.logoutBtn}>🚪 Logout</button>
        </div>
      </div>

      {/* Intake Form - Only for Analyst and Admin */}
      {(user.role === 'analyst' || user.role === 'admin') && (
        <Intake onEvidenceAdded={fetchEvidence} />
      )}

      {/* Statistics Cards */}
      <div style={styles.stats}>
        <div style={styles.statCard}>
          <div style={styles.statIcon}>📊</div>
          <div>
            <h3>Total Evidence</h3>
            <p style={styles.statNumber}>{evidence.length}</p>
          </div>
        </div>
        <div style={styles.statCard}>
          <div style={styles.statIcon}>🔄</div>
          <div>
            <h3>Active Cases</h3>
            <p style={styles.statNumber}>{evidence.filter(i => i.status !== 'Completed' && i.status !== 'Archived').length}</p>
          </div>
        </div>
        <div style={styles.statCard}>
          <div style={styles.statIcon}>✅</div>
          <div>
            <h3>Verified</h3>
            <p style={styles.statNumber}>{evidence.filter(i => i.status === 'Completed').length}</p>
          </div>
        </div>
        <div style={styles.statCard}>
          <div style={styles.statIcon}>📁</div>
          <div>
            <h3>With Files</h3>
            <p style={styles.statNumber}>{evidence.filter(i => i.file_name).length}</p>
          </div>
        </div>
      </div>

      {/* Search Bar */}
      <div style={styles.searchContainer}>
        <input
          type="text"
          placeholder="🔍 Search by case number or description..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          style={styles.searchInput}
        />
      </div>

      {/* Evidence Table */}
      <div style={styles.tableContainer}>
        <table style={styles.table}>
          <thead>
            <tr style={styles.tableHeader}>
              <th style={styles.th}>ID</th>
              <th style={styles.th}>Case Number</th>
              <th style={styles.th}>Description</th>
              <th style={styles.th}>Category</th>
              <th style={styles.th}>Status</th>
              <th style={styles.th}>File</th>
              <th style={styles.th}>Created</th>
              <th style={styles.th}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredEvidence.map(item => (
              <tr key={item.id} style={styles.tableRow}>
                <td style={styles.td}>#{item.id}</td>
                <td style={styles.td}><strong style={{ color: '#38bdf8' }}>{item.case_number}</strong></td>
                <td style={styles.td}>{item.description?.substring(0, 60)}...</td>
                <td style={styles.td}>
                  <span style={styles.categoryBadge}>{item.category}</span>
                </td>
                <td style={styles.td}>
                  {user.role !== 'viewer' ? (
                    <select 
                      value={item.status} 
                      onChange={(e) => updateStatus(item.id, e.target.value)}
                      style={{...styles.statusBadge, backgroundColor: getStatusColor(item.status)}}
                    >
                      {getStatusOptions().map(status => (
                        <option key={status} value={status}>{status}</option>
                      ))}
                    </select>
                  ) : (
                    <span style={{...styles.statusBadge, backgroundColor: getStatusColor(item.status)}}>
                      {item.status}
                    </span>
                  )}
                </td>
                <td style={styles.td}>
                  {item.file_name ? (
                    <span style={styles.fileBadge}>
                      📎 {item.file_name.substring(0, 20)}{item.file_name.length > 20 ? '...' : ''}
                    </span>
                  ) : (
                    <span style={styles.noFile}>No file</span>
                  )}
                </td>
                <td style={styles.td}>{new Date(item.created_at).toLocaleDateString()}</td>
                <td style={styles.td}>
                  <div style={styles.actionButtons}>
                    <button onClick={() => viewDetails(item.id)} style={styles.iconBtn} title="View Details">
                      👁️
                    </button>
                    <button onClick={() => downloadReport(item)} style={styles.iconBtn} title="Download Report">
                      📄
                    </button>
                    {user.role !== 'viewer' && (
                      <>
                        <label style={styles.iconBtn} title="Upload File">
                          📤
                          <input
                            type="file"
                            style={{ display: 'none' }}
                            onChange={(e) => uploadFile(item.id, e.target.files[0])}
                            disabled={uploading[item.id]}
                          />
                        </label>
                        <button 
                          onClick={() => alert(`SHA-256 Hash:\n${item.hash_value || 'Not calculated'}`)} 
                          style={styles.iconBtn} 
                          title="View Hash"
                        >
                          🔑
                        </button>
                      </>
                    )}
                    {user.role === 'admin' && (
                      <button 
                        onClick={() => deleteEvidence(item.id, item.case_number)} 
                        style={{...styles.iconBtn, backgroundColor: '#7f1d1d'}} 
                        title="Delete"
                      >
                        🗑️
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {filteredEvidence.length === 0 && (
          <div style={styles.noData}>
            {searchTerm ? 'No matching evidence found' : 'No evidence records yet. Create your first evidence using the form above!'}
          </div>
        )}
      </div>

      {/* Details Modal */}
      {showDetails && selectedEvidence && (
        <div style={styles.modal} onClick={() => setShowDetails(false)}>
          <div style={styles.modalContent} onClick={(e) => e.stopPropagation()}>
            <div style={styles.modalHeader}>
              <h2>Evidence Details</h2>
              <button onClick={() => setShowDetails(false)} style={styles.closeBtn}>✖</button>
            </div>
            <div style={styles.modalBody}>
              <p><strong>Case Number:</strong> {selectedEvidence.case_number}</p>
              <p><strong>Description:</strong> {selectedEvidence.description}</p>
              <p><strong>Category:</strong> {selectedEvidence.category}</p>
              <p><strong>Status:</strong> {selectedEvidence.status}</p>
              <p><strong>Hash:</strong> <code>{selectedEvidence.hash}</code></p>
              <p><strong>Created By:</strong> {selectedEvidence.created_by}</p>
              <p><strong>Created At:</strong> {new Date(selectedEvidence.created_at).toLocaleString()}</p>
              <hr />
              <h3>Chain of Custody</h3>
              {selectedEvidence.history?.map((log, idx) => (
                <div key={idx} style={styles.logEntry}>
                  <strong>{log.action}</strong><br />
                  <small>By: {log.technician} | {new Date(log.timestamp).toLocaleString()}</small>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const styles = {
  container: { backgroundColor: '#0f172a', minHeight: '100vh', padding: '20px', fontFamily: 'monospace' },
  header: { backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '15px' },
  title: { color: '#38bdf8', margin: 0, fontSize: '24px' },
  subtitle: { color: '#94a3b8', fontSize: '12px', marginTop: '5px' },
  userInfo: { display: 'flex', alignItems: 'center', gap: '20px' },
  userDetails: { textAlign: 'right' },
  userRole: { display: 'block', fontSize: '11px', color: '#38bdf8' },
  userName: { fontSize: '14px', color: '#f8fafc' },
  logoutBtn: { padding: '8px 16px', backgroundColor: '#dc2626', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontFamily: 'monospace' },
  stats: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '20px' },
  statCard: { backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '15px' },
  statIcon: { fontSize: '32px' },
  statNumber: { fontSize: '28px', fontWeight: 'bold', color: '#38bdf8', margin: '5px 0 0 0' },
  searchContainer: { marginBottom: '20px' },
  searchInput: { width: '100%', padding: '12px', backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px', color: '#f8fafc', fontSize: '14px', fontFamily: 'monospace' },
  tableContainer: { backgroundColor: '#1e293b', borderRadius: '8px', overflow: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse', color: '#f8fafc' },
  tableHeader: { backgroundColor: '#0f172a', borderBottom: '1px solid #334155' },
  th: { padding: '12px', textAlign: 'left', fontSize: '12px', color: '#94a3b8' },
  tableRow: { borderBottom: '1px solid #334155', transition: 'background 0.2s' },
  td: { padding: '12px', fontSize: '13px' },
  statusBadge: { padding: '4px 8px', borderRadius: '4px', fontSize: '11px', border: 'none', cursor: 'pointer', color: 'white' },
  categoryBadge: { padding: '2px 6px', backgroundColor: '#0f172a', borderRadius: '4px', fontSize: '11px' },
  fileBadge: { padding: '2px 6px', backgroundColor: '#0f172a', borderRadius: '4px', fontSize: '11px' },
  noFile: { fontSize: '11px', color: '#64748b', fontStyle: 'italic' },
  actionButtons: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  iconBtn: { padding: '5px 8px', backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '4px', cursor: 'pointer', fontSize: '14px' },
  loading: { display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh', color: '#38bdf8', fontSize: '18px' },
  noData: { textAlign: 'center', padding: '40px', color: '#64748b' },
  modal: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modalContent: { backgroundColor: '#1e293b', borderRadius: '8px', maxWidth: '600px', width: '90%', maxHeight: '80vh', overflow: 'auto' },
  modalHeader: { padding: '20px', borderBottom: '1px solid #334155', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  modalBody: { padding: '20px' },
  closeBtn: { background: 'none', border: 'none', color: '#94a3b8', fontSize: '20px', cursor: 'pointer' },
  logEntry: { padding: '10px', margin: '10px 0', backgroundColor: '#0f172a', borderRadius: '4px' }
};

export default Dashboard;
