import React, { useEffect, useState, useCallback } from 'react';
import axios from 'axios';
import Intake from './Intake';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const Dashboard = ({ user, onLogout }) => {
  const [evidence, setEvidence] = useState([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState({});
  const [selectedEvidence, setSelectedEvidence] = useState(null);
  const [showDetails, setShowDetails] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [showBulkUpload, setShowBulkUpload] = useState(false);
  const [showAnalytics, setShowAnalytics] = useState(false);
  const [bulkFiles, setBulkFiles] = useState([]);
  const [bulkUploading, setBulkUploading] = useState(false);

  const fetchEvidence = useCallback(async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get('http://127.0.0.1:8000/api/evidence', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setEvidence(response.data);
    } catch (err) {
      if (err.response?.status === 401) onLogout();
    } finally {
      setLoading(false);
    }
  }, [onLogout]);

  useEffect(() => {
    fetchEvidence();
  }, [fetchEvidence]);

  const updateStatus = async (id, newStatus) => {
    const technician = user.username;
    try {
      const token = localStorage.getItem('token');
      await axios.patch(`http://127.0.0.1:8000/api/evidence/${id}/status`, null, {
        params: { new_status: newStatus, technician },
        headers: { Authorization: `Bearer ${token}` }
      });
      fetchEvidence();
      alert(`Status updated to ${newStatus}`);
    } catch (err) {
      alert('Update failed');
    }
  };

  const uploadFile = async (id, file) => {
    if (!file) return;
    const formData = new FormData();
    formData.append('file', file);
    
    setUploading(prev => ({ ...prev, [id]: true }));
    try {
      const token = localStorage.getItem('token');
      await axios.post(`http://127.0.0.1:8000/api/evidence/${id}/upload`, formData, {
        headers: { Authorization: `Bearer ${token}` }
      });
      alert('File uploaded successfully!');
      fetchEvidence();
    } catch (err) {
      alert('Upload failed');
    } finally {
      setUploading(prev => ({ ...prev, [id]: false }));
    }
  };

  const deleteEvidence = async (id, caseNumber) => {
    if (window.confirm(`Are you sure you want to delete "${caseNumber}"?`)) {
      try {
        const token = localStorage.getItem('token');
        await axios.delete(`http://127.0.0.1:8000/api/evidence/${id}`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        alert('Evidence deleted successfully');
        fetchEvidence();
      } catch (err) {
        alert('Delete failed');
      }
    }
  };

  const downloadTextReport = (item) => {
    const report = `TRACELOCK FORENSIC REPORT
================================
Generated: ${new Date().toLocaleString()}
Generated by: ${user.username} (${user.role})

EVIDENCE DETAILS
----------------
Case Number: ${item.case_number}
Description: ${item.description}
Category: ${item.category}
Status: ${item.status}
Created: ${new Date(item.created_at).toLocaleString()}

FORENSIC INTEGRITY
------------------
SHA-256 Hash: ${item.hash_value || 'Not calculated'}
File Attached: ${item.file_name || 'No file attached'}

This report is digitally signed by TraceLock Forensic System`;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${item.case_number}_Forensic_Report.txt`;
    a.click();
    URL.revokeObjectURL(url);
    alert('Text Report downloaded');
  };

  const generatePDF = async (item) => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`http://127.0.0.1:8000/api/evidence/${item.id}/details`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const fullDetails = response.data;
      
      const doc = new jsPDF();
      
      // Header
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(56, 189, 248);
      doc.setFontSize(20);
      doc.text('TRACELOCK FORENSIC REPORT', 105, 20, { align: 'center' });
      doc.setTextColor(148, 163, 184);
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleString()}`, 105, 30, { align: 'center' });
      doc.text(`Generated by: ${user.username} (${user.role})`, 105, 36, { align: 'center' });
      
      // Evidence Details
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(14);
      doc.text('EVIDENCE DETAILS', 14, 55);
      
      autoTable(doc, {
        startY: 60,
        head: [['Field', 'Value']],
        body: [
          ['Case Number', item.case_number],
          ['Description', item.description],
          ['Category', item.category],
          ['Status', item.status],
          ['Created', new Date(item.created_at).toLocaleString()],
          ['File Name', item.file_name || 'No file attached'],
          ['File Size', item.file_size ? `${(item.file_size / 1024).toFixed(2)} KB` : 'N/A'],
          ['SHA-256 Hash', item.hash_value || 'Not calculated']
        ],
        theme: 'striped',
        headStyles: { fillColor: [56, 189, 248], textColor: [15, 23, 42] },
        styles: { fontSize: 10 }
      });
      
      // Chain of Custody
      doc.addPage();
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(14);
      doc.text('CHAIN OF CUSTODY', 14, 20);
      
      autoTable(doc, {
        startY: 25,
        head: [['Timestamp', 'Action', 'User']],
        body: fullDetails.history?.map(log => [
          new Date(log.timestamp).toLocaleString(),
          log.action,
          log.technician
        ]) || [['No history available', '', '']],
        theme: 'striped',
        headStyles: { fillColor: [56, 189, 248], textColor: [15, 23, 42] }
      });
      
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('Digitally signed by TraceLock Forensic System', 105, 285, { align: 'center' });
        doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
      }
      
      doc.save(`${item.case_number}_Forensic_Report.pdf`);
      alert('PDF Report downloaded');
    } catch (err) {
      alert('PDF generation failed');
    }
  };

  // EXPORT TO EXCEL
  const exportToExcel = () => {
    if (evidence.length === 0) {
      alert('No data to export');
      return;
    }
    
    const headers = ['ID', 'Case Number', 'Description', 'Category', 'Status', 'File Name', 'Hash Value', 'Created Date'];
    const rows = evidence.map(item => [
      item.id,
      item.case_number,
      `"${(item.description || '').replace(/"/g, '""')}"`,
      item.category,
      item.status,
      item.file_name || 'No file',
      item.hash_value || 'Not calculated',
      new Date(item.created_at).toLocaleString()
    ]);
    
    const csvContent = [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `evidence_export_${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    alert(`Exported ${evidence.length} records to CSV`);
  };

  // BULK UPLOAD
  const handleBulkFileSelect = (e) => {
    const files = Array.from(e.target.files);
    setBulkFiles(files);
  };

  const handleBulkUpload = async () => {
    if (bulkFiles.length === 0) {
      alert('Please select files');
      return;
    }
    
    setBulkUploading(true);
    const token = localStorage.getItem('token');
    let success = 0;
    
    for (let i = 0; i < bulkFiles.length; i++) {
      const file = bulkFiles[i];
      try {
        const caseNumber = `BULK-${Date.now()}-${i + 1}`;
        const evidenceRes = await axios.post('http://127.0.0.1:8000/api/evidence', null, {
          params: { case_number: caseNumber, description: `Bulk upload: ${file.name}`, category: 'Digital' },
          headers: { Authorization: `Bearer ${token}` }
        });
        
        const formData = new FormData();
        formData.append('file', file);
        await axios.post(`http://127.0.0.1:8000/api/evidence/${evidenceRes.data.id}/upload`, formData, {
          headers: { Authorization: `Bearer ${token}` }
        });
        success++;
      } catch (err) {
        console.error(`Failed: ${file.name}`);
      }
    }
    
    setBulkUploading(false);
    setBulkFiles([]);
    fetchEvidence();
    alert(`Bulk upload complete! ${success} of ${bulkFiles.length} files uploaded`);
    setShowBulkUpload(false);
  };

  const viewDetails = async (id) => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`http://127.0.0.1:8000/api/evidence/${id}/details`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setSelectedEvidence(response.data);
      setShowDetails(true);
    } catch (err) {
      alert('Failed to load details');
    }
  };

  const getStatusColor = (status) => {
    const colors = { 'Intake': '#f59e0b', 'Scanning': '#3b82f6', 'Analyzing': '#8b5cf6', 'Completed': '#10b981', 'Archived': '#64748b' };
    return colors[status] || '#6b7280';
  };

  const getStatusOptions = () => {
    if (user.role === 'viewer') return [];
    return ['Intake', 'Scanning', 'Analyzing', 'Completed', 'Archived'];
  };

  // Analytics
  const getStatusCounts = () => {
    const counts = { Intake: 0, Scanning: 0, Analyzing: 0, Completed: 0, Archived: 0 };
    evidence.forEach(item => {
      if (counts[item.status] !== undefined) counts[item.status]++;
    });
    return counts;
  };

  const getCategoryCounts = () => {
    const counts = {};
    evidence.forEach(item => {
      counts[item.category] = (counts[item.category] || 0) + 1;
    });
    return counts;
  };

  const filteredEvidence = evidence.filter(item =>
    item.case_number?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.description?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const statusCounts = getStatusCounts();
  const categoryCounts = getCategoryCounts();
  const total = evidence.length;

  const ChartBar = ({ label, count, color }) => {
    const percentage = total > 0 ? (count / total) * 100 : 0;
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
        <div style={{ width: '100px', fontSize: '12px' }}>{label}</div>
        <div style={{ flex: 1, height: '20px', backgroundColor: '#0f172a', borderRadius: '10px', overflow: 'hidden' }}>
          <div style={{ width: `${percentage}%`, height: '100%', backgroundColor: color }} />
        </div>
        <div style={{ width: '80px', fontSize: '11px', color: '#94a3b8' }}>{count} ({percentage.toFixed(0)}%)</div>
      </div>
    );
  };

  if (loading) return <div style={{ color: '#38bdf8', textAlign: 'center', marginTop: '50px', fontSize: '18px' }}>Loading Dashboard...</div>;

  return (
    <div style={{ backgroundColor: '#0f172a', minHeight: '100vh', padding: '20px', fontFamily: 'monospace' }}>
      
      {/* HEADER */}
      <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <div>
          <h1 style={{ color: '#38bdf8', margin: 0, fontSize: '24px' }}>🔒 TraceLock Forensic Suite</h1>
          <p style={{ color: '#94a3b8', fontSize: '12px', marginTop: '5px' }}>Secure Evidence Management System</p>
        </div>
        <div>
          <span style={{ color: '#f8fafc', marginRight: '15px' }}>{user.username} ({user.role.toUpperCase()})</span>
          <button onClick={onLogout} style={{ padding: '8px 16px', backgroundColor: '#dc2626', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>Logout</button>
        </div>
      </div>

      {/* FEATURE BUTTONS */}
      <div style={{ display: 'flex', gap: '15px', marginBottom: '20px', flexWrap: 'wrap' }}>
        <button onClick={() => setShowBulkUpload(!showBulkUpload)} style={{ padding: '10px 20px', backgroundColor: '#38bdf8', color: '#0f172a', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
          📦 Bulk Upload
        </button>
        <button onClick={exportToExcel} style={{ padding: '10px 20px', backgroundColor: '#10b981', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
          📊 Export to Excel
        </button>
        <button onClick={() => setShowAnalytics(!showAnalytics)} style={{ padding: '10px 20px', backgroundColor: '#8b5cf6', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
          📈 Analytics Dashboard
        </button>
      </div>

      {/* BULK UPLOAD SECTION */}
      {showBulkUpload && (
        <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', marginBottom: '20px' }}>
          <h3 style={{ color: '#38bdf8', marginBottom: '15px' }}>📦 Bulk Upload Files</h3>
          <input type="file" multiple onChange={handleBulkFileSelect} style={{ marginBottom: '15px', color: '#f8fafc' }} />
          {bulkFiles.length > 0 && (
            <div>
              <p style={{ color: '#94a3b8', marginBottom: '10px' }}>{bulkFiles.length} file(s) selected</p>
              <button onClick={handleBulkUpload} disabled={bulkUploading} style={{ padding: '10px 20px', backgroundColor: '#10b981', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
                {bulkUploading ? 'Uploading...' : `Upload ${bulkFiles.length} Files`}
              </button>
            </div>
          )}
          <p style={{ color: '#64748b', fontSize: '11px', marginTop: '15px' }}>Select multiple files. Each file will create a new evidence record.</p>
        </div>
      )}

      {/* ANALYTICS DASHBOARD */}
      {showAnalytics && (
        <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', marginBottom: '20px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
            <h3 style={{ color: '#38bdf8', margin: 0 }}>📈 Analytics Dashboard</h3>
            <button onClick={() => setShowAnalytics(false)} style={{ padding: '5px 10px', backgroundColor: '#ef4444', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Close</button>
          </div>
          
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '15px', marginBottom: '20px' }}>
            <div style={{ backgroundColor: '#0f172a', padding: '15px', borderRadius: '8px', textAlign: 'center' }}>
              <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#38bdf8' }}>{total}</div>
              <div style={{ fontSize: '11px', color: '#94a3b8' }}>Total Evidence</div>
            </div>
            <div style={{ backgroundColor: '#0f172a', padding: '15px', borderRadius: '8px', textAlign: 'center' }}>
              <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#38bdf8' }}>{evidence.filter(i => i.file_name).length}</div>
              <div style={{ fontSize: '11px', color: '#94a3b8' }}>With Files</div>
            </div>
            <div style={{ backgroundColor: '#0f172a', padding: '15px', borderRadius: '8px', textAlign: 'center' }}>
              <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#10b981' }}>{evidence.filter(i => i.status === 'Completed').length}</div>
              <div style={{ fontSize: '11px', color: '#94a3b8' }}>Completed</div>
            </div>
            <div style={{ backgroundColor: '#0f172a', padding: '15px', borderRadius: '8px', textAlign: 'center' }}>
              <div style={{ fontSize: '28px', fontWeight: 'bold', color: '#8b5cf6' }}>{evidence.filter(i => i.status === 'Analyzing').length}</div>
              <div style={{ fontSize: '11px', color: '#94a3b8' }}>In Analysis</div>
            </div>
          </div>
          
          <h4 style={{ color: '#f8fafc', marginBottom: '10px' }}>Status Distribution</h4>
          {Object.entries(statusCounts).map(([status, count]) => (
            <ChartBar key={status} label={status} count={count} color={status === 'Intake' ? '#f59e0b' : status === 'Scanning' ? '#3b82f6' : status === 'Analyzing' ? '#8b5cf6' : status === 'Completed' ? '#10b981' : '#64748b'} />
          ))}
          
          <h4 style={{ color: '#f8fafc', marginBottom: '10px', marginTop: '20px' }}>Category Distribution</h4>
          {Object.entries(categoryCounts).map(([category, count]) => (
            <ChartBar key={category} label={category} count={count} color="#38bdf8" />
          ))}
        </div>
      )}

      {/* INTAKE FORM */}
      {(user.role === 'analyst' || user.role === 'admin') && (
        <Intake onEvidenceAdded={fetchEvidence} />
      )}

      {/* STATISTICS CARDS */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px', marginBottom: '20px' }}>
        <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', textAlign: 'center' }}>
          <div style={{ fontSize: '32px' }}>📊</div>
          <h3 style={{ color: '#f8fafc', margin: '10px 0' }}>Total Evidence</h3>
          <p style={{ fontSize: '28px', color: '#38bdf8', margin: 0 }}>{evidence.length}</p>
        </div>
        <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', textAlign: 'center' }}>
          <div style={{ fontSize: '32px' }}>🔄</div>
          <h3 style={{ color: '#f8fafc', margin: '10px 0' }}>Active Cases</h3>
          <p style={{ fontSize: '28px', color: '#38bdf8', margin: 0 }}>{evidence.filter(i => i.status !== 'Completed' && i.status !== 'Archived').length}</p>
        </div>
        <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', textAlign: 'center' }}>
          <div style={{ fontSize: '32px' }}>✅</div>
          <h3 style={{ color: '#f8fafc', margin: '10px 0' }}>Verified</h3>
          <p style={{ fontSize: '28px', color: '#38bdf8', margin: 0 }}>{evidence.filter(i => i.status === 'Completed').length}</p>
        </div>
        <div style={{ backgroundColor: '#1e293b', padding: '20px', borderRadius: '8px', textAlign: 'center' }}>
          <div style={{ fontSize: '32px' }}>📁</div>
          <h3 style={{ color: '#f8fafc', margin: '10px 0' }}>With Files</h3>
          <p style={{ fontSize: '28px', color: '#38bdf8', margin: 0 }}>{evidence.filter(i => i.file_name).length}</p>
        </div>
      </div>

      {/* SEARCH BAR */}
      <input
        type="text"
        placeholder="🔍 Search by case number or description..."
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        style={{ width: '100%', padding: '12px', marginBottom: '20px', backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px', color: '#f8fafc', fontSize: '14px' }}
      />

      {/* EVIDENCE TABLE */}
      <div style={{ backgroundColor: '#1e293b', borderRadius: '8px', overflow: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', color: '#f8fafc' }}>
          <thead>
            <tr style={{ backgroundColor: '#0f172a', borderBottom: '1px solid #334155' }}>
              <th style={{ padding: '12px', textAlign: 'left' }}>ID</th>
              <th style={{ padding: '12px', textAlign: 'left' }}>Case Number</th>
              <th style={{ padding: '12px', textAlign: 'left' }}>Description</th>
              <th style={{ padding: '12px', textAlign: 'left' }}>Category</th>
              <th style={{ padding: '12px', textAlign: 'left' }}>Status</th>
              <th style={{ padding: '12px', textAlign: 'left' }}>File</th>
              <th style={{ padding: '12px', textAlign: 'left' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredEvidence.map(item => (
              <tr key={item.id} style={{ borderBottom: '1px solid #334155' }}>
                <td style={{ padding: '12px' }}>#{item.id}</td>
                <td style={{ padding: '12px', color: '#38bdf8', fontWeight: 'bold' }}>{item.case_number}</td>
                <td style={{ padding: '12px' }}>{item.description?.substring(0, 50)}...</td>
                <td style={{ padding: '12px' }}><span style={{ padding: '2px 6px', backgroundColor: '#0f172a', borderRadius: '4px', fontSize: '11px' }}>{item.category}</span></td>
                <td style={{ padding: '12px' }}>
                  {user.role !== 'viewer' ? (
                    <select value={item.status} onChange={(e) => updateStatus(item.id, e.target.value)} style={{ padding: '4px 8px', borderRadius: '4px', backgroundColor: getStatusColor(item.status), color: 'white', border: 'none', cursor: 'pointer' }}>
                      {getStatusOptions().map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  ) : (
                    <span style={{ padding: '4px 8px', borderRadius: '4px', backgroundColor: getStatusColor(item.status), color: 'white', fontSize: '11px' }}>{item.status}</span>
                  )}
                </td>
                <td style={{ padding: '12px' }}>
                  {item.file_name ? (
                    <span style={{ padding: '2px 6px', backgroundColor: '#0f172a', borderRadius: '4px', fontSize: '11px' }}>📎 {item.file_name.substring(0, 20)}</span>
                  ) : (
                    <span style={{ fontSize: '11px', color: '#64748b' }}>No file</span>
                  )}
                </td>
                <td style={{ padding: '12px' }}>
                  <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                    <button onClick={() => viewDetails(item.id)} style={{ padding: '5px 8px', backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '4px', cursor: 'pointer' }} title="Chain of Custody">👁️</button>
                    <button onClick={() => generatePDF(item)} style={{ padding: '5px 8px', backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '4px', cursor: 'pointer' }} title="PDF Report">📄</button>
                    <button onClick={() => downloadTextReport(item)} style={{ padding: '5px 8px', backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '4px', cursor: 'pointer' }} title="Text Report">📝</button>
                    {user.role !== 'viewer' && (
                      <>
                        <label style={{ padding: '5px 8px', backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '4px', cursor: 'pointer' }} title="Upload File">
                          📤
                          <input type="file" style={{ display: 'none' }} onChange={(e) => uploadFile(item.id, e.target.files[0])} disabled={uploading[item.id]} />
                        </label>
                        <button onClick={() => alert(`SHA-256 Hash:\n${item.hash_value || 'Not calculated'}`)} style={{ padding: '5px 8px', backgroundColor: '#0f172a', border: '1px solid #334155', borderRadius: '4px', cursor: 'pointer' }} title="View Hash">🔑</button>
                      </>
                    )}
                    {user.role === 'admin' && (
                      <button onClick={() => deleteEvidence(item.id, item.case_number)} style={{ padding: '5px 8px', backgroundColor: '#7f1d1d', border: 'none', borderRadius: '4px', cursor: 'pointer' }} title="Delete">🗑️</button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {filteredEvidence.length === 0 && (
          <div style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>
            {searchTerm ? 'No matching evidence found' : 'No evidence records yet. Create your first evidence using the form above!'}
          </div>
        )}
      </div>

      {/* DETAILS MODAL */}
      {showDetails && selectedEvidence && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }} onClick={() => setShowDetails(false)}>
          <div style={{ backgroundColor: '#1e293b', borderRadius: '8px', maxWidth: '600px', width: '90%', maxHeight: '80vh', overflow: 'auto' }} onClick={(e) => e.stopPropagation()}>
            <div style={{ padding: '20px', borderBottom: '1px solid #334155', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h2 style={{ color: '#38bdf8' }}>Chain of Custody</h2>
              <button onClick={() => setShowDetails(false)} style={{ background: 'none', border: 'none', color: '#94a3b8', fontSize: '20px', cursor: 'pointer' }}>✖</button>
            </div>
            <div style={{ padding: '20px' }}>
              <p><strong>Case Number:</strong> {selectedEvidence.case_number}</p>
              <p><strong>Description:</strong> {selectedEvidence.description}</p>
              <p><strong>Category:</strong> {selectedEvidence.category}</p>
              <p><strong>Status:</strong> {selectedEvidence.status}</p>
              <p><strong>Hash:</strong> <code style={{ wordBreak: 'break-all' }}>{selectedEvidence.hash}</code></p>
              <hr style={{ borderColor: '#334155', margin: '15px 0' }} />
              <h3>Activity Log</h3>
              {selectedEvidence.history && selectedEvidence.history.length > 0 ? (
                selectedEvidence.history.map((log, idx) => (
                  <div key={idx} style={{ padding: '10px', margin: '10px 0', backgroundColor: '#0f172a', borderRadius: '4px' }}>
                    <strong>📋 {log.action}</strong><br />
                    <small>👤 {log.technician} | 📅 {new Date(log.timestamp).toLocaleString()}</small>
                  </div>
                ))
              ) : (
                <p style={{ color: '#64748b' }}>No chain of custody records found.</p>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;