import React from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const PDFReport = ({ evidence, user }) => {
  const generatePDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(56, 189, 248);
    doc.setFontSize(20);
    doc.text('TRACELOCK FORENSIC REPORT', 105, 20, { align: 'center' });
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 105, 30, { align: 'center' });
    doc.text(`Generated by: ${user.username} (${user.role})`, 105, 36, { align: 'center' });
    
    // Evidence Details
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.text('EVIDENCE DETAILS', 14, 55);
    
    autoTable(doc, {
      startY: 60,
      head: [['Field', 'Value']],
      body: [
        ['Case Number', evidence.case_number],
        ['Description', evidence.description],
        ['Category', evidence.category],
        ['Status', evidence.status],
        ['Created', new Date(evidence.created_at).toLocaleString()],
        ['File Name', evidence.file_name || 'No file attached'],
        ['File Size', evidence.file_size ? `${(evidence.file_size / 1024).toFixed(2)} KB` : 'N/A'],
        ['SHA-256 Hash', evidence.hash_value || 'Not calculated']
      ],
      theme: 'striped',
      headStyles: { fillColor: [56, 189, 248], textColor: [15, 23, 42] },
      styles: { fontSize: 10 }
    });
    
    // Chain of Custody
    doc.addPage();
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.text('CHAIN OF CUSTODY', 14, 20);
    
    autoTable(doc, {
      startY: 25,
      head: [['Timestamp', 'Action', 'User']],
      body: evidence.history?.map(log => [
        new Date(log.timestamp).toLocaleString(),
        log.action,
        log.technician
      ]) || [['No history available', '', '']],
      theme: 'striped',
      headStyles: { fillColor: [56, 189, 248], textColor: [15, 23, 42] }
    });
    
    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text('Digitally signed by TraceLock Forensic System', 105, 285, { align: 'center' });
      doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    }
    
    doc.save(`${evidence.case_number}_Forensic_Report.pdf`);
  };
  
  return { generatePDF };
};
